### PR TITLE
Bug fixes for filters and pagination

### PR DESCRIPTION
**Pull request by samrawks**
# Bug
- Fixed the styles the search filters (#5)
- Added the icons back to the pagination using Typo3 icon set (#5)

### CODE REVIEW

**Comment by mikestreety** [comment]
@samrawks This looks much better!

Only thing I noticed is the "Show entries" select box is missing it's little chevron to show it is a select box and not an input box

Screenshot 2023-11-03 at 12 52 49

**Comment by mikestreety** [comment]
@samrawks Looking at this again, can the rows have a min-height so they are all the same?

image

Can there also be a bit more padding, as it is currently easy to accidentally click the wrong button either vertically or horizontally 

Might be worth reducing the padding/font size on the buttons themselves a tad too

**Comment by samrawks** [comment]
### Added for #5 
- Select menu icon using default browser option
- Height attributes to table rows to force mininum heights
- Spacing to Approve/Reject buttons

**Comment by mikestreety** [comment]
@zaqmughal-ll You happy?

image

image

**Pull request merged**
